### ISSUE TITLE
Upon loading the favorites explorer can be empty

### ISSUE THREAD

**Issue by fredjeck** [fredjeck/fav#16]
Sometimes the favorites explorer loads-up empty, and I have to either reload or restart VS Code for the favorites to show up

**Comment by SolarTheory** [comment]
> Sometimes the favorites explorer loads-up empty, and I have to either reload or restart VS Code for the favorites to show up

I am no longer having this issue after I did a clean reinstall of VS Code.  It may have been something on my end.  If it shows up again, I will update.  (Meanwhile, there is another unrelated bug that I will detail in a separate Issue).
