### ISSUE TITLE
Request: Moving Sub-Group or Favorite File Link to Top-Level?

### ISSUE THREAD

**Issue by SolarTheory** [fredjeck/fav#18]
Is it currently possible to move a sub-group or favorite link within that group to the very top-level of the hierarchy via the GUI?  Currently, I am having to manually edit the favorites.json file to achieve this (or creating a new group at the top level and moving individual items from the sub-group to the new top-level group, which seems inefficient).

Thanks!

**Comment by fredjeck** [comment]
That's true it's currently not possible to move up a nested group to the top level hierarchy.
I'm taking this one for the next release thanks for submitting !

**Comment by fredjeck** [comment]
Implemented in release 1.6.2
