### ISSUE TITLE
Suggestion: Different 'colors' or 'icons' to differentiate folders that are extension groups from actual folders

### ISSUE THREAD

**Issue by carloscadux** [fredjeck/fav#19]
Hi.
Just a suggestion to assign different 'colors' or 'icons' to folder for differentiating the ones that are extension groups from actual folders (added through 'add folders to favorites' command).
I'm referring to the default/automatic icons assigned by the extension (I'm not requesting folder customization by the user).
Thanks,
Carlos

**Comment by fredjeck** [comment]
Hello and thanks for your proposal, I think it makes totally sense.
To avoid breaking themes, it is better to stay colour neutral and make use of built-in VSCode product icon themes (https://code.visualstudio.com/api/references/icons-in-labels)
I find the 'files' icons to be matching the purpose of the feature (if you see another one which could be more significant just let me know !)

![Sample](https://user-images.githubusercontent.com/15845066/156055029-4d00905c-c6b2-49f8-859a-7367b6185b90.png)

**Comment by carloscadux** [comment]
Thanks for considering the proposal 👍
What about either 'root-folder' or 'file-submodule' icons?

[image: image.png]

**Comment by carloscadux** [comment]
Thanks for considering the proposal 👍
What about either 'root-folder' or 'file-submodule' icons?

![CopyQ LfimzA](https://user-images.githubusercontent.com/7339389/156072376-fa4e2c91-1336-45ee-9414-2da441b9b91c.png)

**Comment by fredjeck** [comment]
Here is what it looks like with the root-folder or file-submodule icons, i'm not fond of them as they tend to complexify the readability.
![root-folder](https://user-images.githubusercontent.com/15845066/156439991-4b331909-c1c8-40d3-8921-0ffe86983475.png)
![submodule](https://user-images.githubusercontent.com/15845066/156439996-823e7030-a8f8-46fd-b6f4-99921b8b497b.png)
The **files** icon captures pretty much the essence of the feature as it is a group of files controlled by a filter

**Comment by carloscadux** [comment]
> I find the 'files' icons to be matching the purpose of the feature
> 
> ![Sample](https://user-images.githubusercontent.com/15845066/156055029-4d00905c-c6b2-49f8-859a-7367b6185b90.png)

I agree.

Just a further thought: 'root-folder' isn't god at all; 'file-submodule' a bit better.
