### ISSUE TITLE
Suggestion: Additional context menu command for files (Open in new window)

### ISSUE THREAD

**Issue by carloscadux** [fredjeck/fav#21]
Hi fredjeck,

Just a suggestion for having an additional context menu command for files:
Open in new window

Thanks,
Carlos

![image](https://user-images.githubusercontent.com/7339389/156225193-29936c03-f1cf-4fb5-9840-7991fcbbd121.png)

**Comment by fredjeck** [comment]
I will take this one for the next release, thanks for submitting !

**Comment by fredjeck** [comment]
This feature will be bundled with the next release which is currently being tested.
