### ISSUE TITLE
Fav not appearing in the in-built VScode extension search when looking for 'favorites' keyword (plural)

### ISSUE THREAD

**Issue by carloscadux** [fredjeck/fav#22]
Just sharing with you that Fav doesn't appear in the in-built VScode extension search when looking for 'favorites' (plural).
When searching for 'favorite' (singular) it is listed.
I don't have any idea how VSCode extension search works, but Fav being listed both through 'favorites' and 'favorite' would increase the likelihood of people seeing and starting using it.
Here is the screen-recording with my test: https://bit.ly/3vXLuzr

**Comment by fredjeck** [comment]
Thanks for the suggestion, I added a couple of other keywords which will hopefully improve how the extension is presented in the search results
