### ISSUE TITLE
Suggestion: Button 'Edit configuration file'

### ISSUE THREAD

**Issue by carloscadux** [fredjeck/fav#23]
Hi.
Just a usability suggestion, to make it simpler/faster to trigger the editing of the 'configuration file' through a button in the UI (screenshot below).
After changing paths in my computer I had to update 'favorites.json' to match them, and if a button was there it would have been handy.
Thank you!

![image](https://user-images.githubusercontent.com/7339389/157880699-b8337b03-b9be-44b8-9845-c17368861c5a.png)

**Comment by fredjeck** [comment]
Packed this suggestion into the next release !
