### ISSUE TITLE
Keyborad shotcuts for movement

### ISSUE THREAD

**Issue by TheElegantCoding** [fredjeck/fav#25]
add commands and shortcuts to move between next favorite file and the previous file

**Comment by fredjeck** [comment]
Hi can you be more precise about your request ? 
Currently :
- You can use the "fav: Focus on explorer view" to open the favorites explorer
- Use arrow keys to navigate and select favorites
- Press enter to open favorites

**Comment by fredjeck** [comment]
Closing as no feedback provided
