### ISSUE TITLE
Add menu and keyboard shortcut 

### ISSUE THREAD

**Issue by TheElegantCoding** [fredjeck/fav#27]
Add the ability to see the file favorites like this and open this menu with a command

![image](https://github.com/fredjeck/fav/assets/70770072/3e67eceb-3baf-4633-8b1e-191f7b1c6c17)

**Comment by fredjeck** [comment]
Just to make sure I understand your request :
Goal is to have a global shortcut which would open a searchbar allowing you to search/filter your favorites and open them.
Like the CTRL+P shortcut somehow.

**Comment by fredjeck** [comment]
Closing as no feedback provided

**Comment by fredjeck** [comment]
Closing as no feedback provided
